//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvaluacionWebApp.Logica.ModeloEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evaluaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Evaluaciones()
        {
            this.Requerimientos = new HashSet<Requerimientos>();
        }
    
        public int id_evaluacion { get; set; }
        public string fecha { get; set; }
        public Nullable<double> peso_antr { get; set; }
        public Nullable<double> talla_antr { get; set; }
        public Nullable<double> imc_antr { get; set; }
        public Nullable<double> peso_ideal_antr { get; set; }
        public Nullable<double> factor_peso_antr { get; set; }
        public Nullable<double> cb_corp { get; set; }
        public Nullable<double> pt_corp { get; set; }
        public Nullable<double> pb_corp { get; set; }
        public Nullable<double> psi_corp { get; set; }
        public Nullable<double> pse_corp { get; set; }
        public Nullable<double> pliegues_corp { get; set; }
        public Nullable<double> cc_corp { get; set; }
        public Nullable<double> carpo_corp { get; set; }
        public Nullable<double> cmb_corp { get; set; }
        public Nullable<double> amb_corp { get; set; }
        public Nullable<double> agb_corp { get; set; }
        public Nullable<double> albumina { get; set; }
        public Nullable<double> creatinina { get; set; }
        public Nullable<double> balance_hidrico { get; set; }
        public Nullable<double> pco2 { get; set; }
        public Nullable<double> pafi { get; set; }
        public Nullable<double> leucocitos { get; set; }
        public Nullable<double> pc_reactiva { get; set; }
        public Nullable<double> hemoglobina { get; set; }
        public Nullable<double> hematrocito { get; set; }
        public Nullable<double> trigliceridos { get; set; }
        public Nullable<double> glicemia { get; set; }
        public Nullable<double> lactato { get; set; }
        public Nullable<double> urea { get; set; }
        public string otros_examenes { get; set; }
        public string diagnostico_nutricional { get; set; }
        public string meta_nutricional { get; set; }
        public string observaciones { get; set; }
        public int id_paciente { get; set; }
        public int id_usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requerimientos> Requerimientos { get; set; }
        public virtual Pacientes Pacientes { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
