//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvaluacionWebApp.Logica.ModeloEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pacientes()
        {
            this.Evaluaciones = new HashSet<Evaluaciones>();
        }
    
        public int id_paciente { get; set; }
        public string nombre { get; set; }
        public string apepat { get; set; }
        public string apemat { get; set; }
        public Nullable<int> rut { get; set; }
        public Nullable<int> edad { get; set; }
        public string sexo { get; set; }
        public string diagnostico { get; set; }
        public Nullable<int> ficha_medica { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public int id_usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evaluaciones> Evaluaciones { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
