//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvaluacionWebApp.Logica.ModeloEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requerimientos
    {
        public int id_requerimiento { get; set; }
        public string tipo { get; set; }
        public string requerimiento { get; set; }
        public string energia { get; set; }
        public string proteina { get; set; }
        public string factor_kcal { get; set; }
        public string factor_prot { get; set; }
        public string cho_porc { get; set; }
        public string cho_gr { get; set; }
        public string lip_porc { get; set; }
        public string lip_gr { get; set; }
        public int id_evaluacion { get; set; }
    
        public virtual Evaluaciones Evaluaciones { get; set; }
    }
}
