//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvaluacionWebApp.Logica.ModeloEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requerimientos
    {
        public int id_requerimiento { get; set; }
        public string tipo { get; set; }
        public Nullable<double> requerimiento { get; set; }
        public Nullable<double> kcaloria { get; set; }
        public Nullable<double> proteina { get; set; }
        public Nullable<double> factor_kcal { get; set; }
        public Nullable<double> factor_prot { get; set; }
        public Nullable<double> cho_porc { get; set; }
        public Nullable<double> cho_gr { get; set; }
        public Nullable<double> lip_porc { get; set; }
        public Nullable<double> lip_gr { get; set; }
        public int id_evaluacion { get; set; }
    
        public virtual Evaluaciones Evaluaciones { get; set; }
    }
}
